name: Lint CloudFormation Templates

on: push

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cfn
        uses: actions/checkout@v2

      - name: Check out code on branch
        uses: actions/checkout@v2

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Testing with CFN Lint Command
        run: |
          cd $GITHUB_WORKSPACE
          for d in $(find / -type d -name "cloudformation") cd $(realpath -s cloudformation);do
            cfn-lint --version $d
            cfn-lint -t ./**/*.yaml $d
          done
          
