name: Lint CloudFormation Templates

on: push

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cfn
        uses: actions/checkout@v2

      - name: Check out code on branch
        uses: actions/checkout@v2

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Testing with CFN Lint Command
        with:
          name: cfn_results
          path: ${{ github.workspace }}
        run: |
          cd $GITHUB_WORKSPACE
          for d in $(find . -type d \(-path './env/**' -or -path './cloudformation/**' \) -exec sh -c '(ls -p "{}"|grep />/dev/null)||echo "{}"' \;); do
            cfn-lint --version $d
            cfn-lint -t ./**/*.yaml $d
          done
          
